version: 2
project_name: oras-macos-vz
env_files:
  gitlab_token: "{{ .Env.GITLAB_TOKEN_FILE }}"
gitlab_urls:
  api: "{{ .Env.CI_API_V4_URL }}"
  download: "{{ .Env.CI_SERVER_URL }}"
  skip_tls_verify: true
  use_package_registry: true
builds:
- main: ./cmd/oras
  binary: ./oras
  env:
  - CGO_ENABLED=0
  flags:
  - -trimpath
  goos:
  - darwin
  goarch:
  - arm64
  ldflags:
  # one-line ldflags to bypass the goreleaser bugs
  # the git tree state is guaranteed to be clean by goreleaser
  # version will be kept as is from the forked original
  - -w -s -buildid= -X oras.land/oras/internal/version.GitCommit={{ .Env.CI_COMMIT_SHA }} -X oras.land/oras/internal/version.BuildMetadata="{{ .Env.CI_COMMIT_REF_NAME }}-macos-vz" -X oras.land/oras/internal/version.GitTreeState=clean
  mod_timestamp: "{{ .Env.CI_COMMIT_TIMESTAMP }}"

archives:
  - format: tar.gz
    files:
    - LICENSE

brews:
- name: oras-macos-vz
  repository:
    owner: tools
    name: homebrew-core
    token: "{{ .Env.GITLAB_PUBLISH_TOKEN }}"
  folder: Formula
  url_template: "{{ .Env.BREW_BASE_URL }}/?owner=fleet&repo=oras-macos-vz&provider=gitlab&tag={{ .Tag }}&artifact_name={{ .ArtifactName }}"
  homepage: "{{ .Env.CI_PROJECT_URL }}"
  description: "MacOS Virtualization OCI registry client - managing macOS Virtual Machine images in the macOS Virtualization Kubelet format"
  skip_upload: false
